### PR TITLE
Laid some ground work to get the "getPokemons()" method working

### PR DESCRIPTION
**Pull request by MikePT28**
Added some files to handle the VarintEncode in a Utils package.

Started working on getNeighbors() and encoding it to assign it to the mq.f1 value. So far it seems to be generating the bytes correctly. More testing needed to figure this out.

The lat and log are hardcoded because I wanted to avoid that exception from being thrown and see if it could carry through the hole try/catch without any issues

### CODE REVIEW

**Comment by fess89** [comment]
You could possibly look into this implementation:
https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/util/Varint.java

**Comment by MikePT28** [comment]
They appear to do the same thing, but I could try and swap them since the one you point to is just one file instead of 3.

**Comment by omkarmoghe** [comment]
lgtm @MikePT28 but do we need to use the hardcoded lat/lon? the location services should work?

**Comment by MikePT28** [comment]
I'm having issues in the Emulator with the location, haven't tried on a physical device. But yeah, I will remove that and connect it to the LocationManager.

Also I changed the files, the resulting ByteString is the same, so all looks good.

**Comment by jmrapp1** [comment]
You should use the [Genymotion emulator](https://www.genymotion.com/). It's 10x faster and offers more support. It will allow you to [spoof your location](http://stackoverflow.com/questions/30709329/give-fake-location-to-genymotion-emulator) as well.

**Pull request merged**
