### PR TITLE
Added permissions for Android 6

### PR DESCRIPTION
**Pull request by Ilya-Gazman**

### CODE REVIEW

**Comment by omkarmoghe** [comment]
@Ilya-Gazman looks good boss, just fix the merge conflicts pl0x :)

**Comment by Ilya-Gazman** [comment]
I think that I merge it, how do I refresh it?

**Comment by jmrapp1** [comment]
You'll have to reupdate this merge with the newest base branch because a lot has changed. Just pull down the new code and then make those changes to the 2 files then recommit

**Comment by Ilya-Gazman** [comment]
Done, please give me some priority, it's my second merge...

**Pull request merged**
