### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by PetrGasparik**

### CODE REVIEW

**Comment by wjwolf79** [comment]
I would suggest changing the 2 instances of ... to use the ellipse character code  `&#8230;`

**Comment by PetrGasparik** [comment]
as of ... to -> … : it would be great to have this character in English version, first ;)

so future translators can base on good text.

**Comment by wjwolf79** [comment]
It is.  😁

**Comment by PetrGasparik** [comment]
I see, changed right after I forked. Not funny :)

**Comment by wjwolf79** [comment]
Yeah, I pushed the English changes right after the Russian translation was put in, so I had to redo it.

**Comment by PetrGasparik** [comment]
I am wonder if I will push new translations through PR every time there is a new string :)

**Pull request merged**
