### PR TITLE
Service Notification

### PR DESCRIPTION
**Pull request by vidarr101**
Ongoing Notification of Pokemon in the area.

Option in settings
Default is off and 60 second refresh period.

### CODE REVIEW

**Comment by s7092910** [comment]
Looks good, but can you use google's material design icon svgs instead of pngs

**Comment by vidarr101** [comment]
updated to SVG, forgot I could use those with a slight conversion

**Comment by s7092910** [comment]
Fix the build error with travis-ci and then you have my approval

**Comment by vidarr101** [comment]
done :-)

**Comment by omkarmoghe** [comment]
lgtm, will merge after conflicts are resolved!

**Comment by vidarr101** [comment]
grumble grumble if CI builds please merge before more conflicts , conflicts make me sad.

**Comment by vidarr101** [comment]
please merge, fixed conflict CI is building

**Pull request merged**
