### PR TITLE
Login clean up

### PR DESCRIPTION
**Pull request by s7092910**
- Added saving the Google Refresh Token and a method to refresh the Google Token if expired
- Removed saving login info in the app settings
- Removed old Login Fragment since it is no longer being used
  -Added in a LoginInfo class that holds the information needed for logging in and refreshing tokens
- Changed the SharedPreference wrapper to store and fetch a LoginInfo object
  -Removed use of PokeGoAPI login methods (They were crap).

### CODE REVIEW

**Comment by Giggitybyte** [comment]
> Added saving the Google Refresh Token and a method to refresh the Google Token if expired

Yes! I've been waiting for this!

**Comment by s7092910** [comment]
It currently doesn't refresh the token, the method is just there

**Comment by axsddlr** [comment]
would be best to submit request minus merge commit, for fast-forward ease

**Comment by s7092910** [comment]
@Ayysir Just so you know, it doesn't matter. When the PRs are merged in, we use merge squashing so that the PR is only 1 commit. It is best to keep the merge commits in there so that we know that they have been merged with the latest stuff.

**Pull request merged**
