### PR TITLE
Added plurals for pokemon count

### PR DESCRIPTION
**Pull request by Kolyall**
added plurals for displaying pokemons count
added pokemon list to each lang for using Translations Editor in Android Studio

### CODE REVIEW

**Comment by igromanru** [comment]
Plural of Pokémon is Pokémon! NOT Pokémon's

**Comment by Kolyall** [comment]
@igromanru but on rus it has plurals

**Comment by PetrGasparik** [comment]
In Czech it has plural also: 1 Pokémon, 2-4 Pokémoni, 5+ Pokémonů

**Comment by Kolyall** [comment]
@omkarmoghe merge conflict fixed

**Comment by Kolyall** [comment]
@PetrGasparik @omkarmoghe @igromanru 
Closed because of ignored by admins 
don't want fix conflicts every day.

**Pull request closed without merging**
