### PR TITLE
Added directions / Remove marker selection/information presentation after long press

### PR DESCRIPTION
**Pull request by jLynx**
Remove marker selection/information presentation after long press
Add Pokemon directions for info panel when tapped

### CODE REVIEW

**Comment by LinkOut** [comment]
Another Map Application? I guess opening GoogleMaps at this point means you got PokemonGo App in background, Pokemap in background, and PokemonGo App will be closed by system.  Useful directions will be inside Pogemap app itself.

**Comment by jLynx** [comment]
@LinkOut it used google maps to open the directions to the selected pokemon. it does not close out of anything

**Comment by LinkOut** [comment]
I mean that: 

```
Intent intent = new Intent(android.content.Intent.ACTION_VIEW,
 +                    Uri.parse("http://maps.google.com/maps?daddr="+ poke.getLatitude() + "," + poke.getLongitude()));
 +            startActivity(intent);
```

Opens google maps application wich is the 3rd application using maps, i guess some of the 3 will be killed by the system and i think will be PokemonGo app... And that will be annoying

**Comment by s7092910** [comment]
@DarkN3ss61 it does start another app tho. I agree with @LinkOut that we should have the PokeMap app to show the direction instead of opening up another another app.

**Comment by jLynx** [comment]
@LinkOut @s7092910 I have not had any of the apps crash for me. they all seem to be 100% stable

**Comment by jLynx** [comment]
Adding it into the same app adds a bunch of unnecessary stuff that is not needed 
https://www.youtube.com/watch?v=HuQDUxGwLPw

**Comment by LinkOut** [comment]
@DarkN3ss61 I understand that the code does what you show in video but the scenario is this:

Im on PokemonGo app, i see a pokemon, i open PokeMap too search it, i found it i want direction, i open GoogleMaps application for directions (another battery drain app coz of live moving etc), then get back to PokemonGo app wich may be closed by the system due to hight amount of memory that GoogleMaps needs... I'm just saying that for me directions must be inside Pokemap application, and not opening GoogleMaps one :D

**Comment by jLynx** [comment]
@LinkOut Well I just made another video and everything stayed running with nothing being reloaded at all https://www.youtube.com/watch?v=-Uk5spDMXwo

**Comment by s7092910** [comment]
@DarkN3ss61 When developing for any platform, you always develop for the lowest spec you are supporting. Not all phones have 3 GB of Ram these days. On top of that, some phones have app kill processes that are quite strict and close apps fairly often. On top of that you have to do a little bit more work by switching between 3 apps instead of just 2. 

Keep in mind you aren't developing for you, you are developing for your users. The UI and much of the app has to be "Keep it simple, Stupid" or KISS. Which you make it so easy and intuitive to use. For instance a user will probably want to have the directions inside the app instead of opening another app. So they can see if the pokemon expires while traveling to that spot.

**Comment by socrates2510** [comment]
@DarkN3ss61 independent if your phone closes or not other apps, I can assure you that it will close apps in mine. I don't like this, it will open Gmaps by accident on me.

Maybe with a different activation.

**Comment by jLynx** [comment]
@s7092910 Fair enough, I will close this and make another pull with just the "Remove marker selection/information presentation after long press" Fix

**Comment by socrates2510** [comment]
@DarkN3ss61 don't worry about the remove marker selection, that's in my PR with the persistance of previous scans.

**Pull request closed without merging**
