### PR TITLE
Change scan time from 33ms to 133ms #319

### PR DESCRIPTION
**Pull request by cwizard**
Change scan time from 33ms to 133ms #319

### CODE REVIEW

**Comment by s7092910** [comment]
Looks good to me

**Comment by kyr0** [comment]
Well, 133ms is a lot slower. There is a tradeoff between stability and speed here, but a 19 cell range call (3 steps) will always take between 3 and 4 seconds then (2.5 sec only sleep time). Compared to 33ms, what we have now, where this is only 0.6 sec. sleep time. 

Well, maybe we should instead create a config UI/setting for this in the SharedPreferences and set a default to 66ms or so... This would already be twice the sleep time and increate the stability by far. Rest is up to the user then :)

**Comment by blastagator** [comment]
Perhaps make an "advanced" configuration button with settings like this inside it.  Of course, a stable default would be good, but this would allow user to compensate for servers being slow/unstable, if necessary.

**Comment by omkarmoghe** [comment]
cool, merge upstream and we can merge

**Comment by comann** [comment]
Duplicate.

**Pull request closed without merging**
