### PR TITLE
[Milestone 0.1 Feature] Lured Pokemon

### PR DESCRIPTION
**Pull request by s7092910**
- Added in fetching data for Lured Pokemon
- Added in Settings a check box for showing Lured Pokemon

Completes Issue  #94

### CODE REVIEW

**Comment by blastagator** [comment]
This doesn't seem to be working.  Looking at lured pokemon in game and never see them appear on pokemap.

**Comment by s7092910** [comment]
@blastagator You need to enable it in the settings. It is turned off by default.

**Comment by blastagator** [comment]
I have it enabled.

**Comment by s7092910** [comment]
The servers are having stability issues. So that might be the reason.

**Comment by blastagator** [comment]
Updated to latest build, still doesn't seem to be working.  Has someone confirmed it was working?

**Comment by s7092910** [comment]
I just tested it and can confirm that it is working. It won't show a difference between lure pokemon or normal pokemon on the map.

**Comment by socrates2510** [comment]
It shows some errors on my end.

**Pull request merged**
