### PR TITLE
0.31 Server Update

### PR DESCRIPTION
**Pull request by pillisan42**
Changelog 
Add Vibration on Service Notification when new pokemon are found
Sort Pokemon by distance in the list
Adjust Waiting time before sending a request to the server to 6 seconds
Fix default preferences to get pokemon around tree steps area for the notification service
Display The time before the next update on the service
Update pokemon position when resuming pokemap activity

### CODE REVIEW

**Comment by zorakirby** [comment]
don't we only need 5 seconds between each request I thought?

**Comment by lumcory** [comment]
was working early but doesn't seem like it's picking up anything anymore. server patched?

**Comment by Malouff** [comment]
Can you please add a custom notification sound option too? 

I would like to play "Who's That Pokémon?"

**Comment by pillisan42** [comment]
@zorakirby yeah 5 seconds should be enough but i would like to make sure that nothing was lost
@Malouff That's a great idea I thought about made the phone ringing but i don't have implemented yet.

**Pull request closed without merging**
