### PR TITLE
Created PokéMap launcher icon

### PR DESCRIPTION
**Pull request by wjwolf79**
default Android head bugs me... call it OCD. lol.  I'm not a designer by any means, but it's at least better than the default (imo).

### CODE REVIEW

**Comment by filfat** [comment]
I don't know how I feel about having text on an app icon, can we hold of on this a little bit while I look into creating a mock-up?

**Comment by Mahonster** [comment]
+1 on filfat!

Not a bad logo at all, I would just prefer something materially designed.

**Comment by omkarmoghe** [comment]
agreed, check the #design channel in the slack. there are some cool material design icons to work off of

**Comment by wjwolf79** [comment]
it was a quick and dirty.  I just wanted to see something other than the default icon.  I've got no commitments to it, so feel free to delete the request if you wish.  I test on my actual phone (GS7 on Android 6.0.1), not an emulator, so multiple default launcher icons bug me.

**Comment by filfat** [comment]
I quickly sketched up an icon, still need quite a lot of work (test which colours that works best etc), but I'm thinking something in that this.

**Comment by omkarmoghe** [comment]
join the slack channel #design. we'll make a PR for the final icon once yall hash it out in there!

**Pull request closed without merging**
