### PR TITLE
Settings preference for changing color of map location marker

### PR DESCRIPTION
**Pull request by Everis**
Simple settings for changing colour of map location marker icon to Black or White.

### CODE REVIEW

**Comment by omkarmoghe** [comment]
cool, we might end up replacing the crosshare with something in the future, but unsure as of now. can you fix the conflicts so we can merge?

**Comment by Everis** [comment]
Basically any different icons could be easily added. Maybe I will make some other more variable solution in future ;)

**Comment by kyr0** [comment]
Maybe we should change the crosshair automatically based on the map used. Night: Dark maps white crosshair; Day: Normal maps, dark crosshair

**Comment by Everis** [comment]
Conflicts fixed.

**Comment by Everis** [comment]
Come on. Just merge it, or close it :) I am tired of constant fixing of merge conflicts.

**Pull request closed without merging**
