### PR TITLE
Login Screen and Google Authentication 

### PR DESCRIPTION
**Pull request by s7092910**
- Added a Login Screen with both Google and PTC login support
- Cleaned up the Android Manifest so that it is easy to change the launching activity without changing the icon, name, etc.
- Added a warning to not use your main pokemon go account on the login screen.
- After Login, it takes you to the Main Activity and creates an AuthInfo object for the PokeGoApi and saves it through saving the activity and recreating it.
- Fixed a few bugs and added a UI folder for activities and things related to the UI. Moved the Main Activity to it.

Completed Issue #18,  #60

### CODE REVIEW

**Comment by omkarmoghe** [comment]
nice one! lgtm, lets have at least one more person look at this

**Comment by omkarmoghe** [comment]
@s7092910 dev diverged a little do you mind fixing the conflicts real quick?

**Comment by comann** [comment]
@s7092910 

After you have recieved the GoogleAuthToken make sure to call

``` java
nianticManager.setGoogleAuthToken(authToken)
```

This ensures that the manager is properly setup with the login credentials.

**Comment by s7092910** [comment]
@comann @omkarmoghe merged the latests changes from develop.

**Pull request merged**
