### PR TITLE
Removed annoying auto popup information

### PR DESCRIPTION
**Pull request by jLynx**
Removed annoying auto popup information for first found pokemon.
Before you had to dismiss the auto popup before you can select the location behind it as well as it could hide potential pokemon behind it. 
This has now been resolved.

### CODE REVIEW

**Comment by s7092910** [comment]
I believe all your previous commits have been reverted back as it shows only 1 file has been changed and it is only 1 line.

**Comment by jLynx** [comment]
Yeah its only one line that needs to be removed

**Comment by s7092910** [comment]
So you are only removing that 1 line and not the other 5 commits before you merged the git into your branch?

**Comment by jLynx** [comment]
Sorry i'm still new to git, im only trying to create a pull request for "Remove annoying auto popup informations." and not the other 6 as they have already been merged

**Comment by s7092910** [comment]
Ah I see, just make sure next time you rebase before you start working on something. But besides that it looks fine for me.

**Comment by christiancoleman** [comment]
In the interest of keeping our commit history full of meaningful commits, I would close this out and create another pull request (or edit this one if that can be done /shrug) with the two good commits you have. Let me know if you need help tackling this.  An easy way to do it would be to delete your fork, create new fork, make first commit changes and commit, make second commit changes and commit. Then create a PR from your fork.

**Comment by jLynx** [comment]
@christiancoleman  Please add me on skype: joel2nz as I need a bit of help with git before I create another pull request

**Comment by jLynx** [comment]
Moved to #127

**Pull request closed without merging**
