### PR TITLE
Adds PokeGoApi as Gradle Dependency

### PR DESCRIPTION
**Pull request by comann**
This api is still in active development, so I ended up using there jar dependency they put on jitpack.io. Here is the [repo](https://github.com/Grover-c13/PokeGOAPI-Java).  Due to all of there dependencies and our existing proto classes I ran into dexing issues therefore had to add a proguard file.

### CODE REVIEW

**Comment by comann** [comment]
Here is a short sample (taken from there source):
- Does auth with PTC.
- Sets the geo location
- Finds the catchable pokemon
- Prints out Results

``` java
        OkHttpClient http = new OkHttpClient();
        AuthInfo auth = null;

        try {
            auth = (new PtcLogin(http)).login(ExampleLoginDetails.LOGIN, ExampleLoginDetails.PASSWORD);
            PokemonGo e = new PokemonGo(auth, http);
            e.setLocation(-32.058087D, 115.744325D, 0.0D);
            List catchablePokemon = e.getMap().getCatchablePokemon();
            System.out.println("Pokemon in area:" + catchablePokemon.size());
            Iterator var5 = catchablePokemon.iterator();

            while(var5.hasNext()) {
                CatchablePokemon cp = (CatchablePokemon)var5.next();
                EncounterResult encResult = cp.encounterPokemon();
                if(encResult.wasSuccessful()) {
                    System.out.println("Encounted:" + cp.getPokemonId());
                    CatchResult result = cp.catchPokemon();
                    System.out.println("Attempt to catch:" + cp.getPokemonId() + " " + result.getStatus());
                }
            }
        } catch (RemoteServerException | LoginFailedException var9) {
            Log.e("Main", "Failed to login or server issue: ", var9);
        }
```

**Comment by s7092910** [comment]
Looks good. Tho we might have to use our own PTC login due to the login for that API does thread locking. And for an app that is a no go, specially with how bad the pokemon go servers have been.

**Comment by MikePT28** [comment]
Can't we just force the API's PTC to run in a background thread??

**Comment by s7092910** [comment]
We technically good, but it wouldn't be exactly clean.

**Pull request merged**
