### PR TITLE
Add searching steps to settings

### PR DESCRIPTION
**Pull request by socrates2510**
I added values 1-5 for a better user experience, but it is not restricted by code.
I've seen people using 15.

### CODE REVIEW

**Comment by jLynx** [comment]
Could have a slider and when you take it past x it says "are you sure, you are risking a ban"

**Comment by rohanjain1** [comment]
why the 30 odd commits for 43 lines of code? If you could re-raise a PR where all this has been cleaned up, it really helps avoid issues with merging and keep the branch stable. 
You can create a patch of this, then apply it on a cleaned up and updated version of your fork. That should resolve it. Thanks.

**Comment by fess89** [comment]
seems fine, I wonder where the 30 commits come from

**Comment by rohanjain1** [comment]
I'm guessing he did a lot of hit and try commits to get to the final code. And even if most of it is reverted code, it's messy to have all that history on the main branch. a clean single commit with final vetted code is the way to go.

**Comment by socrates2510** [comment]
@rohanhjain1 please just check the changes files. Not the commits. If checking commits only the last 2 are not in upstream. 

I promised that I would solve that in this commit but get carried away and didn't do it. Check the the 3rd commit bottom up was already merged in a previous PR.

**Comment by omkarmoghe** [comment]
@rohanjain1 @socrates2510 doesnt matter how many commits are in the branch anyways, we always squash and merge so it will only be 1 commit to the main dev branch

**Pull request merged**
