### PR TITLE
Removes internal proto files

### PR DESCRIPTION
**Pull request by comann**
Removes the PokemonOuterClass. Adds in a using a background handler and PtcLogin class for login. Slightly alters the OkHttpClient to handle longer timeouts. Also adds in a dexcount plugin. This really is not necessary anymore, but its in there if people want to see how large the pokegoapi really is.

Okay so there is a lot more in this PR then orginally thought. 

The current flow is the the UI listeners will invoke a method on the NianticManager that will work in the background using its background thread handler. The NianticManager then passes the result to the Notifier whose responsibility is to dispatch messages on the UI thread using its handler.

---Maybe this should go in the WIKI---

### CODE REVIEW

**Comment by omkarmoghe** [comment]
@comann Build is failing :/ might be a issue with proguard?

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT.
     Required by:
         Pokemap:app:unspecified
```

lgtm otherwise :smile:

**Comment by omkarmoghe** [comment]
lgtm otherwise :smile:

**Comment by rohanjain1** [comment]
If this is gonna do what I think it's gonna do... I.e. get me out of DexOverflow hell, then this is exactly what's needed to fix this project up for real dev. Iv already setup what we discussed but couldn't even test once because of the goddamn build errors

**Comment by rohanjain1** [comment]
If this is gonna do what I think it's gonna do... I.e. get me out of DexOverflow hell, then this is exactly what's needed to fix this project up for real dev. Iv already setup what we discussed but couldn't even test once because of the goddamn build errors

**Pull request merged**
